services:
  payment-service:
    build: .
    ports:
      - "8083:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - MONGODB_DB_NAME=payment_db
      - MP_ACCESS_TOKEN=${MP_ACCESS_TOKEN}
      - MP_POS_ID=${MP_POS_ID}
      - MP_BASE_URL=${MP_BASE_URL}
      - ORDER_STATUS_URL=${ORDER_STATUS_URL}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
