sonar.sources=src
sonar.tests=tests
sonar.exclusions=src/main.py,src/config.py,**/__init__.py

sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml
sonar.projectKey=DiegodeSalles_FIAP-SOAT-PAYMENT-MICROSERVICE
sonar.organization=diegodesalles