apiVersion: v1
kind: Service
metadata:
  name: mongodb-payment
  namespace: fastfood
spec:
  selector:
    app: mongodb-payment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
