apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: fastfood
type: Opaque
data:
  MP_ACCESS_TOKEN: QVBQX1VTUi02MDE4NzM4NzIwODg4MjI0LTA1MjgyMi05MGE5ZTY5YzUzNDUwYTMzMWQxMjZhODYyZTM1MjdlMS0yNDYzMTMwMTA3
  MP_POS_ID: ZmlhcGxhbmNoZXM=
  MP_BASE_URL: aHR0cHM6Ly9hcGkubWVyY2Fkb3BhZ28uY29tLw==
