apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: fastfood
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - name: payment
          image: 674080151285.dkr.ecr.us-east-1.amazonaws.com/fiap-fastfood-ms-payment
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: MONGODB_URL
            - name: MONGODB_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: MONGODB_DB_NAME
            - name: MP_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: MP_ACCESS_TOKEN
            - name: MP_POS_ID
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: MP_POS_ID
            - name: MP_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: MP_BASE_URL
            - name: ORDER_STATUS_URL
              valueFrom:
                secretKeyRef:
                  name: payment-secret
                  key: ORDER_STATUS_URL