apiVersion: v1
kind: Secret
metadata:
  name: payment-secret
  namespace: fastfood
type: Opaque
data:
  MP_ACCESS_TOKEN: {{MP_ACCESS_TOKEN}}
  MP_POS_ID: {{MP_POS_ID}}
  MP_BASE_URL: {{MP_BASE_URL}}
  MONGODB_URL: {{MONGODB_URL}}