name: Build
on:
  push:
  branches:
      - main
      - develop
  pull_request:
  types: [opened, synchronize, reopened]
jobs:
  sonarqube:
  name: SonarQube Cloud
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v6
    with:
      fetch-depth: 0
  - name: Setup Python
    uses: actions/setup-python@v6
    with:
      python-version: 3.13
  - name: SonarQube Scan
    uses: SonarSource/sonarqube-scan-action@v7
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}